-- The seating plan: which shows exist, and which seat labels are valid within each.
--
-- WHY this table exists at all, and why it is populated by migration rather than an admin API:
-- two of this service's three refusal causes require knowing what is real. A request naming a
-- show this service has never heard of, or a seat label that show's plan has never heard of, can
-- only be told apart from "the seats are already held" if something records what SHOULD exist,
-- independent of what has been claimed so far. No catalogue service exists anywhere in this
-- project's roadmap (research.md, Assumptions; spec.md Clarifications), so this service owns its
-- seating plan locally, and the only way anything enters it is a versioned migration -- there is
-- deliberately no HTTP surface to add a show at runtime, so the seat pool the step-9 load test
-- contends over cannot be edited by accident (FR-033, FR-034).

CREATE TABLE shows (
    -- Generated by the DATABASE, not the application, because a show is seeded data rather than
    -- something a request creates. Contrast with order-service's orders.id, which the
    -- application assigns before the row exists so it can double as the saga correlation id --
    -- no equivalent need exists here.
    show_id     UUID         PRIMARY KEY DEFAULT gen_random_uuid(),

    -- For diagnosis only; nothing branches on this value. A request identifies a show by its
    -- show_id, carried on OrderCreated -- never by name.
    name        VARCHAR(200) NOT NULL,

    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Seat labels live in their own table, keyed on (show_id, seat_label), rather than as an array
-- or JSON column on shows.
--
-- WHY the composite primary key is the point rather than an implementation detail: a seat label
-- is meaningful only relative to its show. "A1" in one show and "A1" in another are two entirely
-- different seats, and this key says so directly -- there is no way to ask "does A1 exist"
-- without also naming which show is meant. It also makes the existence check FR-033 requires a
-- single indexed lookup per seat, not a scan.
CREATE TABLE show_seats (
    show_id     UUID         NOT NULL REFERENCES shows (show_id) ON DELETE CASCADE,
    seat_label  VARCHAR(16)  NOT NULL,

    PRIMARY KEY (show_id, seat_label)
);

-- The seed: exactly two shows, for two different reasons (spec.md Clarifications,
-- session 2026-08-27).
--
-- "Load Test Hall" carries EXACTLY the ten seats the step-9 k6 load test contends over -- not
-- nine, not eleven. That test asserts exactly 10 of 1,000 concurrent requests succeed; changing
-- this count without changing that assertion silently breaks the one number the whole load test
-- is built around (FR-035, SC-001).
--
-- "Second Stage" exists purely so a test can prove per-show scoping actually works. It reuses the
-- label 'A1' on purpose: a seat label valid in one show must be meaningless in another, and that
-- claim can only be exercised if a second show with an overlapping label exists to test it
-- against.
--
-- WHY these are the ONLY seeded shows, and why this seed must never grow to satisfy a test's
-- appetite (FR-036): tests needing larger pools -- SC-002's 500 overlapping requests, SC-003's
-- 500 disjoint ones -- provision their own shows and seats (SeatingPlanFixture, T140) rather than
-- enlarging this one. Seeding a large venue instead was rejected during clarification because
-- tests sharing one pool interfere with each other unless each carefully partitions it, which
-- makes failures depend on execution order, and because it would ship data to every environment
-- that exists only to be tested against.
INSERT INTO shows (name) VALUES ('Load Test Hall');
INSERT INTO shows (name) VALUES ('Second Stage');

INSERT INTO show_seats (show_id, seat_label)
SELECT s.show_id, seat_label
FROM shows s
CROSS JOIN unnest(ARRAY['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5']) AS seat_label
WHERE s.name = 'Load Test Hall';

INSERT INTO show_seats (show_id, seat_label)
SELECT s.show_id, seat_label
FROM shows s
CROSS JOIN unnest(ARRAY['A1', 'A2', 'A3']) AS seat_label
WHERE s.name = 'Second Stage';
