-- The durable reservation: the authoritative record that an order holds a set of seats.
--
-- WHY this is authoritative and Redis is not (research.md R4, R14; FR-014): Redis arbitrates
-- contention because it is fast and its holds expire on their own -- exactly what makes it wrong
-- to trust after a restart. This environment runs Redis with `--save ""`, so a restart empties it
-- completely. PostgreSQL survives that. The fast store is rebuilt FROM this table on startup
-- (SeatLockRebuilder, T179) -- never the other direction.

CREATE TABLE reservations (
    -- The value announced as `reservationId` on SeatsReserved (FR-011). Generated by the
    -- application rather than the database, so the id exists before the row does and can be
    -- embedded in the outbox row written in the very same transaction (ReservationService,
    -- T160).
    reservation_id    UUID          PRIMARY KEY,

    -- UNIQUE, not merely indexed. A second line of defence behind the idempotency guard
    -- (processed_messages, V3): even if that guard were somehow bypassed, the database itself
    -- still refuses a second reservation for one order.
    order_id          UUID          NOT NULL UNIQUE,

    -- Deliberately not a foreign key into any orders table: order-service owns that table in its
    -- own schema, and a cross-service constraint would make this service's writes depend on
    -- another service's schema being reachable, which is exactly the coupling a choreographed
    -- saga exists to avoid.
    show_id           UUID          NOT NULL REFERENCES shows (show_id),

    -- Only HELD and EXPIRED are reachable in this build step. COMMITTED and RELEASED are
    -- declared now, matching ReservationStatus.java (T123), so steps 4 and 5 fill in a
    -- TRANSITION rather than migrate this constraint and every existing row to admit a new
    -- value.
    status            VARCHAR(16)   NOT NULL,

    -- The moment announced as `lockExpiresAt` on SeatsReserved. Computed from the SAME instant as
    -- the outbox row's occurredAt (OutboxWriter, T159): the frozen contract requires the lapse to
    -- fall strictly after the announcement's own timestamp and refuses to construct otherwise, so
    -- deriving the two values at different times risks building a message that can never be sent.
    lock_expires_at   TIMESTAMPTZ   NOT NULL,

    -- Hibernate's @Version (FR-012). Checked on every UPDATE; a writer working from a stale copy
    -- updates zero rows and is told it lost the race, rather than silently overwriting the
    -- winner. Retried exactly once on that failure (FR-013).
    version           BIGINT        NOT NULL DEFAULT 0,

    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT reservations_status_known
        CHECK (status IN ('HELD', 'EXPIRED', 'COMMITTED', 'RELEASED'))

    -- A reservation is NEVER DELETED (FR-021). The record of why an order failed is what makes a
    -- stalled saga diagnosable, and step 5's release path acts on a row that still exists. There
    -- is no DELETE against this table anywhere in this service.
);

-- The seats one reservation claims. A child table rather than an array column on reservations,
-- for the same reason order_seats is a child table of orders in order-service: a composite
-- primary key makes a duplicate seat on one reservation impossible IN THE DATABASE, and this
-- table is what the partial index below needs to attach to.
CREATE TABLE reservation_seats (
    reservation_id  UUID         NOT NULL REFERENCES reservations (reservation_id),
    seat_label      VARCHAR(16)  NOT NULL,

    -- Denormalised from the parent reservation. A partial unique index cannot reference a joined
    -- table, and the uniqueness enforced below is scoped PER SHOW, so show_id has to live on this
    -- row itself. Written once at INSERT and never updated afterwards, so it cannot drift from
    -- its parent (data-model.md).
    show_id         UUID         NOT NULL,

    -- NULL while the seat is claimed (parent status HELD or COMMITTED); set once the claim ends
    -- (EXPIRED or RELEASED). Deliberately NOT a duplicate of the parent's status column -- it
    -- answers a different question, "is this seat claimed right now", which is true for two
    -- different parent states and false for the other two. The mapping is maintained in exactly
    -- one service method (ReservationService, T160), so there is exactly one place to verify it
    -- holds.
    released_at     TIMESTAMPTZ,

    PRIMARY KEY (reservation_id, seat_label)
);

-- THE GUARANTEE THAT SURVIVES REDIS BEING WRONG (research.md R5; FR-020).
--
-- If lock_seats.lua -- the one piece of this service left for a human to write by hand -- is ever
-- mis-implemented, this index is what stops a mistake there from actually double-booking a seat
-- rather than merely appearing to. The failure mode becomes a REJECTED booking, never a
-- double-sold one. LiveSeatConstraintIT (T147, SC-017) proves this by bypassing Redis entirely.
--
-- WHY the predicate is `released_at IS NULL` rather than something comparing lock_expires_at to
-- now(): PostgreSQL requires a partial index's predicate to be IMMUTABLE, and `now() >
-- lock_expires_at` is not -- its result changes with the clock, not with the row -- so a
-- liveness rule defined by TIME cannot be expressed as a constraint at all. That is the concrete
-- reason the EXPIRED state exists (FR-017): liveness has to be a STORED FACT, transitioned by
-- application code the instant it stops being true, rather than a comparison every reader
-- repeats.
CREATE UNIQUE INDEX ux_reservation_seat_live
    ON reservation_seats (show_id, seat_label)
    WHERE released_at IS NULL;
