-- The transactional outbox: a durable record that a message must be sent.
--
-- TRADEOFF: this is the SECOND outbox in the system, and it is a copy of order-service's
-- V2__create_outbox.sql rather than a shared module (research.md R8). The constitution requires
-- an abstraction to be justified by an existing, demonstrated need rather than a hypothetical
-- one; two instances of a pattern is the point at which that need first becomes VISIBLE, not yet
-- the point at which it is demonstrated. Extraction is revisited if a third service needs one --
-- recorded here so that decision is made deliberately rather than by accumulation.
--
-- WHY this table exists at all, unchanged from order-service's reasoning: deciding an outcome
-- and telling the rest of the system about it are two systems -- a database and a broker -- that
-- cannot be committed as one. Crash between them here and either a seat is held with nothing
-- downstream knowing (FR-025's own version of the gap step 2 closed from the other side), or an
-- outcome is announced that was never actually decided. The reservation (or its absence), the
-- processed-message row, and a row in THIS table are written together in ReservationService's one
-- transaction (T160); a background relay sends the message afterwards.

CREATE TABLE outbox (
    -- The recording sequence, and therefore the ordering the relay must preserve. Same caveat as
    -- order-service's: identity values are handed out at INSERT but rows become visible at
    -- COMMIT, so two concurrent inserts can commit in the opposite order to their ids. This
    -- service is not exposed to that -- one order's outcome is decided by exactly one consumed
    -- message, so two rows for one aggregate are never written at once.
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The order this message concerns. Deliberately NOT a foreign key into reservations, for the
    -- same reason order-service's outbox does not reference orders: the outbox is a log of things
    -- that must be said, not a child of the aggregate it describes. This is also what lets a
    -- refusal be recorded here with no reservation row at all (SEATS_NOT_FOUND, SHOW_NOT_FOUND,
    -- SEATS_ALREADY_HELD never create a reservation).
    aggregate_id  UUID         NOT NULL,

    -- The CHANNEL NAME the message goes to -- Topics.SEATS_RESERVED or Topics.SEATS_REJECTED from
    -- common-events, never a literal (OutboxWriter, T159). Storing the destination rather than a
    -- Java class name means the relay never has to map types to channels at send time; it reads a
    -- column and sends.
    event_type    VARCHAR(64)  NOT NULL,

    -- The message, serialized ONCE when this row was written, sent by the relay verbatim. What a
    -- consumer receives is decided at recording time and cannot drift from a later deployment.
    payload       JSONB        NOT NULL,

    -- W3C Trace Context, captured from the message-processing span that decided this outcome.
    -- Without these two columns SC-015's single connected trace breaks in two at this exact
    -- point: order-service's own outbox carried the trace this far, and this row is what carries
    -- it onward through the second gap.
    traceparent   VARCHAR(64),
    tracestate    VARCHAR(512),

    -- PENDING -> PUBLISHED, or PENDING -> PARKED. Authoritative.
    status        VARCHAR(16)  NOT NULL DEFAULT 'PENDING',

    -- Failed send attempts. Reaching the configured limit is what parks the row, which is what
    -- stops a genuinely unsendable message being retried until the end of time.
    attempts      INTEGER      NOT NULL DEFAULT 0,

    -- Why the most recent attempt failed, so a parked row explains itself without a log search.
    last_error    TEXT,

    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published_at  TIMESTAMPTZ,

    CONSTRAINT outbox_status_known
        CHECK (status IN ('PENDING', 'PUBLISHED', 'PARKED')),

    -- Stops status and published_at drifting apart -- the failure mode of carrying two pieces of
    -- redundant state at all. status is authoritative; published_at is the TIME of publication.
    CONSTRAINT outbox_published_consistent
        CHECK ((status = 'PUBLISHED') = (published_at IS NOT NULL))
);

-- Serves both halves of the relay's claim query: the main scan and the MIN(id)-per-aggregate
-- subquery that guarantees per-order ordering (FR-026).
--
-- PARTIAL -- the WHERE clause is the point. Only outstanding work is indexed, so this service's
-- cost is proportional to its BACKLOG, not to how many outcomes it has ever announced.
CREATE INDEX idx_outbox_pending
    ON outbox (aggregate_id, id)
    WHERE status = 'PENDING';

-- Serves the guard that stops the relay stepping OVER a parked row and publishing a later
-- message for the same order out of sequence. Tiny by construction: a healthy service has zero
-- rows here.
CREATE INDEX idx_outbox_parked
    ON outbox (aggregate_id, id)
    WHERE status = 'PARKED';
