-- The transactional outbox: a durable record that a message must be sent.
--
-- WHY this table exists at all. Accepting an order means two things must happen together: the order
-- must be stored, and the rest of the system must be told it exists. Those are two systems -- a
-- database and a broker -- and they cannot be committed as one. Crash between them and you either
-- lose an order the buyer was told was accepted, or announce an order that does not exist.
--
-- The outbox removes the second system from the critical moment. The order row and a row in THIS
-- table are written in one ordinary database transaction, which is atomic for free. A background
-- relay sends the message afterwards. What remains is not "did both happen" but "the send might
-- happen twice" -- a far weaker problem, and one consumers already have to solve.

CREATE TABLE outbox (
    -- The recording sequence, and therefore the ordering the relay must preserve.
    --
    -- CAVEAT worth knowing: identity values are handed out at INSERT, but rows become visible at
    -- COMMIT. Two concurrent inserts can commit in the opposite order to their ids. This system is
    -- not exposed to that, because an order advances one saga step at a time and each step is driven
    -- by exactly one consumed message, so two rows for one aggregate are never written at once. If a
    -- later step introduces concurrent writes for a single order, that assumption breaks and the fix
    -- is a per-aggregate advisory lock held across the insert.
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The order this message concerns. Deliberately NOT a foreign key: the outbox is a log of things
    -- that must be said, not a child of the order. A constraint here would force a decision about
    -- what happens to already-sent messages when an order is archived, and would block a later step
    -- from recording a message about anything that is not an order.
    aggregate_id  UUID         NOT NULL,

    -- The CHANNEL NAME the message goes to, e.g. 'order.created' -- taken from Topics in
    -- common-events, never a literal. Storing the destination rather than a Java class name means
    -- the relay never has to map types to channels at send time; it reads a column and sends.
    event_type    VARCHAR(64)  NOT NULL,

    -- The message, serialized ONCE when this row was written, and sent by the relay verbatim.
    --
    -- WHY serialize now rather than at send time: what a consumer receives is then decided at
    -- recording time and cannot drift. Serializing later means a deployment between recording and
    -- sending silently changes a message that was already promised.
    --
    -- TRADEOFF: jsonb normalises the document -- object keys are reordered and insignificant
    -- whitespace dropped -- so the bytes read back are not byte-identical to those written. TEXT
    -- would preserve them exactly. jsonb is chosen anyway because consumers parse JSON rather than
    -- hashing bytes, and being able to read and query payloads directly is worth a great deal when
    -- a saga has stalled and you need to see what was actually recorded.
    payload       JSONB        NOT NULL,

    -- W3C Trace Context, captured from the accepting request.
    --
    -- The outbox deliberately breaks the chain of execution: the request commits and returns, and
    -- the message is sent later, on a different thread, possibly minutes afterwards. Without these
    -- two values the tracing UI shows two unrelated fragments instead of one story. They live as
    -- COLUMNS rather than inside payload, so the frozen message contracts stay limited to business
    -- facts and a change to how the system is traced can never force a contract version bump.
    traceparent   VARCHAR(64),
    tracestate    VARCHAR(512),

    -- PENDING -> PUBLISHED, or PENDING -> PARKED. Authoritative.
    status        VARCHAR(16)  NOT NULL DEFAULT 'PENDING',

    -- Failed send attempts. Reaching the configured limit is what parks the row, which is what stops
    -- a genuinely unsendable message being retried until the end of time.
    attempts      INTEGER      NOT NULL DEFAULT 0,

    -- Why the most recent attempt failed, so a parked row explains itself without a log search.
    last_error    TEXT,

    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published_at  TIMESTAMPTZ,

    CONSTRAINT outbox_status_known
        CHECK (status IN ('PENDING', 'PUBLISHED', 'PARKED')),

    -- WHY carry both status and published_at when the original design used "published_at IS NULL"
    -- alone to mean outstanding: that works for two states and cannot express a third, and parking
    -- needs a third. status is authoritative and published_at is the TIME of publication. This
    -- constraint is what stops two pieces of redundant state drifting apart, which is the failure
    -- mode of carrying redundant state at all.
    CONSTRAINT outbox_published_consistent
        CHECK ((status = 'PUBLISHED') = (published_at IS NOT NULL))
);

-- Serves both halves of the relay's claim query: the main scan and the MIN(id)-per-aggregate
-- subquery that guarantees per-order ordering.
--
-- PARTIAL -- the WHERE clause is the point. Only outstanding work is indexed, so a published row
-- leaves the index entirely. The relay's cost is therefore proportional to the BACKLOG rather than
-- to the table, and a table holding ten million sent messages polls exactly as fast as an empty one.
CREATE INDEX idx_outbox_pending
    ON outbox (aggregate_id, id)
    WHERE status = 'PENDING';

-- Serves the guard that stops the relay stepping OVER a parked row and publishing a later message
-- for the same order out of sequence. Tiny by construction: a healthy system has zero rows here.
CREATE INDEX idx_outbox_parked
    ON outbox (aggregate_id, id)
    WHERE status = 'PARKED';
