package com.marketplace.inventory.outbox;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.Getter;

/**
 * A durable statement that a message must be sent, written in the same transaction as the seat
 * decision that caused it.
 *
 * <p>Ported from order-service's {@code OutboxRecord} (research.md R8) — this is the second outbox
 * in the system, deliberately a copy rather than a shared module. The pattern itself needs no change
 * to fit this service: a database and a message broker still cannot be committed together, so the
 * decision recorded here — {@code seats.reserved} or {@code seats.rejected} — is written to the same
 * database as the reservation (or its absence), in one genuinely atomic transaction, and a background
 * relay sends it afterwards. The remaining risk is still that a message is sent twice, which
 * consumers already suppress by identity, rather than that a decision is lost, which nothing could
 * repair.
 */
@Entity
@Table(name = "outbox")
@Getter
public class OutboxRecord {

	/**
	 * The recording sequence, and the order the relay must publish in.
	 *
	 * <p>Generated by the database, unlike this service's own {@link com.marketplace.inventory.domain.Reservation}
	 * identifier. A monotonic number is wanted here rather than a UUID precisely because it defines
	 * an order.
	 *
	 * <p>CAVEAT, unchanged from order-service: identity values are handed out when a row is
	 * <em>inserted</em>, but rows become visible when their transaction <em>commits</em>. Two
	 * concurrent inserts can therefore commit in the opposite order to their ids. This service is not
	 * exposed to that — one order's outcome is decided by exactly one consumed message, so two
	 * records for one order are never written concurrently.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * The order this message concerns — still the order id, even when the message is a refusal with
	 * no corresponding reservation. Also the Kafka partition key, so ordering in this table and
	 * ordering on the channel derive from the same value (FR-024).
	 */
	@Column(name = "aggregate_id", nullable = false)
	private UUID aggregateId;

	/**
	 * The channel the message goes to — {@code Topics.SEATS_RESERVED} or {@code Topics.SEATS_REJECTED}
	 * from {@code common-events}, never a literal typed here. Storing the destination rather than a
	 * class name means the relay reads a column and sends, with no type-to-channel mapping at send
	 * time.
	 */
	@Column(name = "event_type", nullable = false, length = 64)
	private String eventType;

	/**
	 * The serialized message, written once and sent verbatim.
	 *
	 * <p>{@code @JdbcTypeCode(SqlTypes.JSON)} is what maps this String to the {@code jsonb} column;
	 * without it Hibernate sends a {@code varchar} and PostgreSQL refuses the type. The field stays a
	 * String because this class must never parse the payload — deciding the content at recording time
	 * is the guarantee, and re-serializing at send time would quietly reopen the gap it closes.
	 */
	@JdbcTypeCode(SqlTypes.JSON)
	@Column(nullable = false, columnDefinition = "jsonb")
	private String payload;

	/**
	 * W3C trace context captured when this record was written, so the relay can continue the
	 * consuming request's trace rather than starting an unrelated one — the second half of SC-015's
	 * single connected trace, the first half being order-service's own outbox row.
	 *
	 * <p>Nullable on purpose: a record written outside a traced context — by a test, or by some
	 * future scheduled process — has no context to store, and must still be sent rather than
	 * stranded.
	 */
	@Column(length = 64)
	private String traceparent;

	@Column(length = 512)
	private String tracestate;

	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 16)
	private OutboxStatus status;

	@Column(nullable = false)
	private int attempts;

	@Column(name = "last_error")
	private String lastError;

	@Column(name = "created_at", nullable = false)
	private Instant createdAt;

	@Column(name = "published_at")
	private Instant publishedAt;

	/** Required by JPA. Not for application code. */
	protected OutboxRecord() {
	}

	public OutboxRecord(UUID aggregateId, String eventType, String payload,
			String traceparent, String tracestate) {
		this.aggregateId = Objects.requireNonNull(aggregateId, "aggregateId");
		this.eventType = Objects.requireNonNull(eventType, "eventType");
		this.payload = Objects.requireNonNull(payload, "payload");
		this.traceparent = traceparent;
		this.tracestate = tracestate;
		this.status = OutboxStatus.PENDING;
		this.attempts = 0;
	}

	// The table's created_at column is NOT NULL DEFAULT now(), but Hibernate generates an INSERT
	// that names every mapped column explicitly -- including this one, as NULL, if the Java field
	// was never set. An explicit NULL overrides the database's DEFAULT rather than falling through to
	// it, so without this callback every insert violates the NOT NULL constraint.
	@PrePersist
	void onInsert() {
		this.createdAt = Instant.now();
	}

	/**
	 * Records that the broker acknowledged this message.
	 *
	 * <p>Both fields move together because a CHECK constraint requires it: {@code published_at} is
	 * non-null exactly when the status is {@code PUBLISHED}. Setting one without the other is
	 * rejected by the database rather than producing a row that half-means something.
	 */
	public void markPublished(Instant when) {
		this.status = OutboxStatus.PUBLISHED;
		this.publishedAt = Objects.requireNonNull(when, "when");
	}

	/**
	 * Records that an attempt to send failed. The record stays {@code PENDING} and will be retried.
	 *
	 * <p>Note what this does NOT do: it does not decide whether the record has failed often enough to
	 * give up on. Counting is the record's business; deciding when the count is too high is the
	 * relay's.
	 */
	public void recordFailure(String error) {
		this.attempts++;
		this.lastError = error;
	}

	/** Gives up on this record permanently. Nothing retries a parked record without a human. */
	public void park() {
		this.status = OutboxStatus.PARKED;
	}

	// No equals or hashCode, deliberately -- the opposite decision to this service's own Reservation,
	// for the identical reason order-service's OutboxRecord makes the same choice: the id here is
	// assigned by the DATABASE, so it is null until the row is inserted. An id-based hash code would
	// therefore change during persist and lose the object from any HashSet holding it. Java's
	// identity semantics are correct for an entity like this.
}
